// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYPqu813R5d2J0mVBqlXgDSw7h6-i9Ys0',
    appId: '1:354755073751:android:0078b7aa0f709eef684292',
    messagingSenderId: '354755073751',
    projectId: 'smart-lion',
    storageBucket: 'smart-lion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIw1QB5sCFAtDVY52NDLlgi50xey4C5ks',
    appId: '1:354755073751:ios:21827e7bbde69d7c684292',
    messagingSenderId: '354755073751',
    projectId: 'smart-lion',
    storageBucket: 'smart-lion.appspot.com',
    iosClientId: '354755073751-9kcimsnohvkc1flkn7l0cv842s1r71rn.apps.googleusercontent.com',
    iosBundleId: 'com.smartlion.mobile',
  );
}
